/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PatientRouteImport } from './routes/Patient'
import { Route as IndexRouteImport } from './routes/Index'
import { Route as DoctorRouteImport } from './routes/Doctor'
import { Route as AdminRouteImport } from './routes/Admin'
import { Route as AboutRouteImport } from './routes/About'

const PatientRoute = PatientRouteImport.update({
  id: '/Patient',
  path: '/Patient',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/Index',
  path: '/Index',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctorRoute = DoctorRouteImport.update({
  id: '/Doctor',
  path: '/Doctor',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/Admin',
  path: '/Admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/About',
  path: '/About',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/About': typeof AboutRoute
  '/Admin': typeof AdminRoute
  '/Doctor': typeof DoctorRoute
  '/Index': typeof IndexRoute
  '/Patient': typeof PatientRoute
}
export interface FileRoutesByTo {
  '/About': typeof AboutRoute
  '/Admin': typeof AdminRoute
  '/Doctor': typeof DoctorRoute
  '/Index': typeof IndexRoute
  '/Patient': typeof PatientRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/About': typeof AboutRoute
  '/Admin': typeof AdminRoute
  '/Doctor': typeof DoctorRoute
  '/Index': typeof IndexRoute
  '/Patient': typeof PatientRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/About' | '/Admin' | '/Doctor' | '/Index' | '/Patient'
  fileRoutesByTo: FileRoutesByTo
  to: '/About' | '/Admin' | '/Doctor' | '/Index' | '/Patient'
  id: '__root__' | '/About' | '/Admin' | '/Doctor' | '/Index' | '/Patient'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRoute
  DoctorRoute: typeof DoctorRoute
  IndexRoute: typeof IndexRoute
  PatientRoute: typeof PatientRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/Patient': {
      id: '/Patient'
      path: '/Patient'
      fullPath: '/Patient'
      preLoaderRoute: typeof PatientRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Index': {
      id: '/Index'
      path: '/Index'
      fullPath: '/Index'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Doctor': {
      id: '/Doctor'
      path: '/Doctor'
      fullPath: '/Doctor'
      preLoaderRoute: typeof DoctorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Admin': {
      id: '/Admin'
      path: '/Admin'
      fullPath: '/Admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/About': {
      id: '/About'
      path: '/About'
      fullPath: '/About'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  AboutRoute: AboutRoute,
  AdminRoute: AdminRoute,
  DoctorRoute: DoctorRoute,
  IndexRoute: IndexRoute,
  PatientRoute: PatientRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
